from sys import stdout

TABLE_SIZE = 256

# White Balance Scaling (0.0 to 1.0)
# Adjust these based on your specific panel's look
# Usually Green is brightest, so we might pull it back to 0.9
# Blue often needs to be stronger (1.0), Red around 0.8-0.9
RED_CAP = 0.988
GREEN_CAP = 1.00
BLUE_CAP = 1.00

# CCM cross-channel shifts — nur zur Dokumentation/Vorschau hier,
# die eigentliche Wirkung passiert zur Compile-Zeit in hub75.hpp.
# shift=31 → deaktiviert, shift=6 → 1.6%, shift=7 → 0.8%
CCM_SHIFTS = {
    "RG": 6,   # green → red
    "RB": 31,  # blue  → red     (off)
    "GR": 31,  # red   → green   (off)
    "GB": 7,   # blue  → green
    "BR": 31,  # red   → blue    (off)
    "BG": 31,  # green → blue    (off)
}

CHANNELS = [
    ("RED",   RED_CAP),
    ("GREEN", GREEN_CAP),
    ("BLUE",  BLUE_CAP),
]


def cie1931(L):
    L *= 100.0
    if L <= 8:
        return ((L + 16.0) / 116.0 - 4.0 / 29.0) * 3.0 * (6.0 / 29.0) ** 2
    else:
        return ((L + 16.0) / 116.0) ** 3


def make_table(resolution, cap):
    """Return a list of TABLE_SIZE rounded integer values."""
    return [
        round(cie1931(float(L) / (TABLE_SIZE - 1)) * (resolution - 1) * cap)
        for L in range(TABLE_SIZE)
    ]


def write_table(name, values):
    stdout.write(f"static const uint16_t CIE_{name}[{TABLE_SIZE}] = {{")
    for i, v in enumerate(values):
        if i % 16 == 0:
            stdout.write("\n    ")
        stdout.write("% 5d," % v)
    stdout.write("\n};\n\n")


def write_ccm_summary():
    stdout.write("// CCM Cross-term summary (shift → approximate percentage):\n")
    for key, shift in CCM_SHIFTS.items():
        if shift >= 31:
            pct = 0.0
            state = "disabled"
        else:
            pct = 100.0 / (1 << shift)
            state = "active"
        src = key[1]  # second char = source channel
        dst = key[0]  # first char  = destination channel
        stdout.write(
            f"//   CCM_{key}_SHIFT={shift:2d}  →  {pct:.1f}% of {src} "
            f"added into {dst}  ({state})\n"
        )
    stdout.write("\n")


def write_hpp():
    stdout.write("// Deduced from https://jared.geek.nz/2013/02/linear-led-pwm/\n")
    stdout.write("// The CIE 1931 lightness formula is what actually describes how we perceive light.\n")
    stdout.write("\n")
    stdout.write("// Generated by cie.py — do not edit manually.\n")
    stdout.write("\n")
    write_ccm_summary()

    # ── SEPARATE_CIE_CHANNELS == true ────────────────────────────────────────
    stdout.write("#if SEPARATE_CIE_CHANNELS == true\n")

    for bitplanes, resolution in [(10, 1024), (8, 256)]:
        if bitplanes == 10:
            stdout.write(f"#if BITPLANES == {bitplanes}\n")
        else:
            stdout.write(f"#elif BITPLANES == {bitplanes}\n")

        for name, cap in CHANNELS:
            write_table(name, make_table(resolution, cap))

    stdout.write("#endif\n")   # BITPLANES
    stdout.write("\n")

    # ── SEPARATE_CIE_CHANNELS == false (shared table) ────────────────────────
    stdout.write("#else\n")

    for bitplanes, resolution in [(10, 1024), (8, 256)]:
        if bitplanes == 10:
            stdout.write(f"#if BITPLANES == {bitplanes}\n")
        else:
            stdout.write(f"#elif BITPLANES == {bitplanes}\n")

        # Use GREEN as the reference channel for the shared table
        # (GREEN_CAP == 1.0, so this matches the original CIE[] table exactly)
        # Empty name → variable is named "CIE" (write_table prepends "CIE_")
        # We write the array declaration manually to get the exact name "CIE".
        values = make_table(resolution, GREEN_CAP)
        stdout.write(f"static const uint16_t CIE[{TABLE_SIZE}] = {{")
        for i, v in enumerate(values):
            if i % 16 == 0:
                stdout.write("\n    ")
            stdout.write("% 5d," % v)
        stdout.write("\n};\n")

    stdout.write("#endif\n")   # BITPLANES
    stdout.write("#endif\n")   # SEPARATE_CIE_CHANNELS


write_hpp()